import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [data, setData] = useState([]);
  const [message, setMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  async function getData() {
    try {
      setIsLoading(true);
      setMessage('');
      const response = await fetch('/api/check', {
        headers: {
          authorization: process.env.NEXT_PUBLIC_APP_KEY,
        },
      });
      const { error, releases, success } = await response.json();

      if (success) {
        if (releases.length > 0) {
          setData(releases);
        } else {
          setMessage('No results');
        }
      } else {
        throw new Error(error);
      }
    } catch (error) {
      setMessage(error.message);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <>
      <Head>
        <title>Scrape City</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Scrape City</h1>
        <button disabled={isLoading} onClick={getData}>
          {isLoading ? 'Checking...' : 'Check Releases'}
        </button>
        {data.length > 0 ? (
          <ul className={styles.data}>
            {data.map(({ link, title }) => (
              <li key={link}>
                <a href={link} rel="noreferrer noopener" target="_blank">
                  {title}
                </a>
              </li>
            ))}
          </ul>
        ) : null}
        <div className={styles.data}>{message}</div>
      </main>
    </>
  );
}
