name: cron job
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: send mail
        run: |
          curl --request POST \
          --url 'https://scrape-city.vercel.app/api/mail' \
          --header 'Authorization: ${{ secrets.ACTION_KEY }}'
